### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by Banyan083214** [Banyan083214/furima-40391#21]
・フリマアプリのURL
https://furima-40391.onrender.com/

・Basic認証ID　tajima       パスワード　　0324

・出品者用
メールアドレス   tajima@tajima
パスワード           tajima1

・購入者用
メールアドレス   furima@furima
パスワード           furimama1

**Comment by Banyan083214** [comment]
修正点
購入者用のパスワードはfurima1です
ご確認お願い致します。

**Comment by motomuun** [comment]
@Banyan083214 さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]
**商品出品機能の確認**

- [ ] **入力された販売価格によって、販売手数料や販売利益が変わること(JavaScriptを使用して実装すること)**
エラーハンドリングによって出品ページに戻ると、販売手数料や利益が変わらなくなります。何度でも変わるように修正をお願いします。

- [ ] **販売手数料と販売利益は、小数点以下を切り捨てて表示すること**
販売手数料と利益の合計が、販売価格と一致しません。一致するように修正をお願いします。
<img width="616" alt="スクリーンショット 2024-03-19 10 11 43" src="https://github.com/Banyan083214/furima-40391/assets/65059944/0088c159-a9a9-45d1-817f-d951d6fda52f">

**商品編集機能の確認**

- [ ] **ログイン状態の場合でも、自身が出品していない商品の商品情報編集ページへ遷移しようとすると、商品の販売状況に関わらずトップページに遷移すること**
自身が出品していない売却済みの商品の商品情報編集ページへ遷移しようとすると、エラーページに遷移します。トップページに遷移するように修正をお願いします。


**その他**
※こちらは要件には含まれていませんが、修正することで、よりアプリの完成度が高くなるので共有します。
- [ ] **「ピックアップカテゴリー　新規投稿商品」の文字列が重複しています。重複しないように修正をお願いします。**

<img width="588" alt="スクリーンショット 2024-03-19 10 19 32" src="https://github.com/Banyan083214/furima-40391/assets/65059944/486ddda9-367e-42c7-8f14-711ced741f57">




修正が完了しましたら、一度ご自身の本番環境で正しく動作しているか確認してみましょう。
修正内容が反映されていることが確認できましたら、再度以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by Banyan083214** [comment]
ご確認ありがとうございます。
修正致しましたのでご確認お願い致します。

**Comment by snkw-works** [comment]
@Banyan083214 さん、修正とご提出ありがとうございます‼︎
正常に動作することが確認できました！ **LGTM** です✨　
おめでとうございます🎉
着実に技術力が身につき、実用的なアプリになってきてますね（^^）

**※確認したのは必須機能のみです。追加実装した機能については確認しておりません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるか、再度ご自身でご確認をお願い致します。**
**※Github上の最終課題の履歴はここまで頑張ってきた証です。削除せず大切に保管するようにしましょう。**

![lgtm_01](https://user-images.githubusercontent.com/54050089/186354234-2de2a3d1-500d-4164-81d5-7585cdd03227.png)
